<?php
$query = " 
CREATE TABLE IF NOT EXISTS `_DB_PREFIX_loffc_block` (
  `id_loffc_block` int(11) NOT NULL AUTO_INCREMENT,
  `width` float(10,2) NOT NULL,
  `show_title` tinyint(1) NOT NULL,
  `id_position` tinyint(2) NOT NULL,
  PRIMARY KEY (`id_loffc_block`)
) ENGINE=_MYSQL_ENGINE_  DEFAULT CHARSET=utf8 AUTO_INCREMENT=60 ;

INSERT INTO `_DB_PREFIX_loffc_block` (`id_loffc_block`, `width`, `show_title`, `id_position`) VALUES
(61, 0.00, 1, 2),
(62, 0.00, 1, 2),
(63, 0.00, 1, 2),
(64, 0.00, 0, 1),
(65, 0.00, 0, 1),
(66, 0.00, 1, 2),
(67, 0.00, 0, 2);

CREATE TABLE IF NOT EXISTS `_DB_PREFIX_loffc_block_item` (
  `id_loffc_block_item` int(11) NOT NULL AUTO_INCREMENT,
  `id_loffc_block` int(11) NOT NULL,
  `type` varchar(25) NOT NULL,
  `link` varchar(2000) NOT NULL,
  `linktype` varchar(25) NOT NULL,
  `link_content` varchar(2000) NOT NULL,
  `module_name` varchar(100) NOT NULL,
  `hook_name` varchar(100) NOT NULL,
  `latitude` varchar(25) NOT NULL,
  `longitude` varchar(25) NOT NULL,
  `addthis` tinyint(1) NOT NULL,
  `show_title` tinyint(1) NOT NULL DEFAULT '1',
  `target` varchar(20) NOT NULL DEFAULT '_self',
  `position` int(11) NOT NULL,
  PRIMARY KEY (`id_loffc_block_item`)
) ENGINE=_MYSQL_ENGINE_  DEFAULT CHARSET=utf8 AUTO_INCREMENT=93 ;

INSERT INTO `_DB_PREFIX_loffc_block_item` (`id_loffc_block_item`, `id_loffc_block`, `type`, `link`, `linktype`, `link_content`, `module_name`, `hook_name`, `latitude`, `longitude`, `addthis`, `show_title`, `target`, `position`) VALUES
(100, 63, 'link', '', 'cms', '3', '', '', '', '', 0, 1, '', 0),
(101, 62, 'link', '', 'category', '4', '', '', '', '', 0, 1, '', 0),
(102, 61, 'link', '', 'category', '1', '', '', '', '', 0, 1, '', 0),
(104, 61, 'link', '', 'category', '4', '', '', '', '', 0, 1, '_self', 1),
(105, 61, 'link', '', 'cms', '3', '', '', '', '', 0, 1, '_self', 2),
(106, 61, 'link', '', 'cms', '5', '', '', '', '', 0, 1, '_self', 3),
(107, 61, 'link', '', 'category', '4', '', '', '', '', 0, 1, '_self', 4),
(108, 62, 'link', '', 'category', '5', '', '', '', '', 0, 1, '_self', 1),
(109, 62, 'link', '', 'cms', '3', '', '', '', '', 0, 1, '_self', 2),
(110, 62, 'link', '', 'cms', '5', '', '', '', '', 0, 1, '_self', 3),
(111, 62, 'link', '', 'category', '4', '', '', '', '', 0, 1, '_self', 4),
(115, 63, 'link', '', 'cms', '5', '', '', '', '', 0, 1, '_self', 1),
(116, 63, 'link', '', 'category', '4', '', '', '', '', 0, 1, '_self', 2),
(117, 63, 'link', '', 'category', '5', '', '', '', '', 0, 1, '_self', 3),
(118, 63, 'link', '', 'category', '5', '', '', '', '', 0, 1, '_self', 4),
(133, 62, 'link', '', 'cms', '2', '', '', '', '', 0, 1, '', 5),
(144, 64, 'module', '', '', '', 'blocknewsletter', 'displayfooter', '', '', 0, 0, '', 0),
(145, 65, 'custom_html', '', '', '', '', '', '', '', 0, 0, '', 0),
(146, 66, 'module', '', '', '', 'blockcategories', 'displayfooter', '', '', 0, 0, '', 0),
(147, 67, 'module', '', '', '', 'blocklanguages', 'displaytop', '', '', 0, 0, '', 0),
(148, 67, 'module', '', '', '', 'blockcurrencies', 'displaytop', '', '', 0, 0, '', 1),
(149, 67, 'custom_html', '', '', '', '', '', '', '', 0, 0, '', 2);


CREATE TABLE IF NOT EXISTS `_DB_PREFIX_loffc_block_item_lang` (
  `id_loffc_block_item` int(11) NOT NULL,
  `id_lang` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  `text` text NOT NULL,
  PRIMARY KEY (`id_loffc_block_item`,`id_lang`)
) ENGINE=_MYSQL_ENGINE_ DEFAULT CHARSET=utf8;

INSERT INTO `_DB_PREFIX_loffc_block_item_lang` (`id_loffc_block_item`, `id_lang`, `title`, `text`) VALUES
(0, 1, 'item 1', ''),
(0, 2, 'item 1', ''),
(0, 3, 'item 1', ''),
(0, 5, 'item 1', ''),
(0, 6, 'item 1', ''),
(100, 1, 'Phasellus purus', ''),
(100, 2, 'Phasellus purus', ''),
(100, 3, 'Phasellus purus', ''),
(100, 4, 'Phasellus purus', ''),
(100, 5, 'Phasellus purus', ''),
(100, 6, 'Phasellus purus', ''),
(100, 7, 'Phasellus purus', ''),
(100, 8, 'Phasellus purus', ''),
(100, 9, 'Phasellus purus', ''),
(101, 1, 'Laoreet sed', ''),
(101, 2, 'Laoreet sed', ''),
(101, 3, 'Laoreet sed', ''),
(101, 4, 'Laoreet sed', ''),
(101, 5, 'Laoreet sed', ''),
(101, 6, 'Laoreet sed', ''),
(101, 7, 'Laoreet sed', ''),
(101, 8, 'Laoreet sed', ''),
(101, 9, 'Laoreet sed', ''),
(102, 1, 'Morbi odio', ''),
(102, 2, 'Morbi odio', ''),
(102, 3, 'Morbi odio', ''),
(102, 4, 'Elementum faucibus', ''),
(102, 5, 'Morbi odio', ''),
(102, 6, 'Morbi odio', ''),
(102, 7, 'Morbi odio', ''),
(102, 8, 'Morbi odio', ''),
(102, 9, 'Morbi odio', ''),
(104, 1, 'Elementum faucibus', ''),
(104, 2, 'Elementum faucibus', ''),
(104, 3, 'Elementum faucibus', ''),
(104, 4, 'Elementum faucibus', ''),
(104, 5, 'Elementum faucibus', ''),
(104, 6, 'Elementum faucibus', ''),
(104, 7, 'Elementum faucibus', ''),
(104, 8, 'Elementum faucibus', ''),
(104, 9, 'Elementum faucibus', ''),
(105, 1, 'Tristique turpis', ''),
(105, 2, 'Tristique turpis', ''),
(105, 3, 'Tristique turpis', ''),
(105, 4, 'Tristique turpis', ''),
(105, 5, 'Tristique turpis', ''),
(105, 6, 'Tristique turpis', ''),
(105, 7, 'Tristique turpis', ''),
(105, 8, 'Tristique turpis', ''),
(105, 9, 'Tristique turpis', ''),
(106, 1, 'Nulla quam', ''),
(106, 2, 'Nulla quam', ''),
(106, 3, 'Nulla quam', ''),
(106, 4, 'Nulla quam', ''),
(106, 5, 'Nulla quam', ''),
(106, 6, 'Nulla quam', ''),
(106, 7, 'Nulla quam', ''),
(106, 8, 'Nulla quam', ''),
(106, 9, 'Nulla quam', ''),
(107, 1, 'Laoreet sed', ''),
(107, 2, 'Laoreet sed', ''),
(107, 3, 'Laoreet sed', ''),
(107, 4, 'Nulla quam', ''),
(107, 5, 'Laoreet sed', ''),
(107, 6, 'Laoreet sed', ''),
(107, 7, 'Laoreet sed', ''),
(107, 8, 'Laoreet sed', ''),
(107, 9, 'Laoreet sed', ''),
(108, 1, 'Tristique turpis', ''),
(108, 2, 'Tristique turpis', ''),
(108, 3, 'Tristique turpis', ''),
(108, 4, 'Tristique turpis', ''),
(108, 5, 'Tristique turpis', ''),
(108, 6, 'Tristique turpis', ''),
(108, 7, 'Tristique turpis', ''),
(108, 8, 'Tristique turpis', ''),
(108, 9, 'Tristique turpis', ''),
(109, 1, 'Morbi odio', ''),
(109, 2, 'Morbi odio', ''),
(109, 3, 'Morbi odio', ''),
(109, 4, 'Morbi odio', ''),
(109, 5, 'Morbi odio', ''),
(109, 6, 'Morbi odio', ''),
(109, 7, 'Morbi odio', ''),
(109, 8, 'Morbi odio', ''),
(109, 9, 'Morbi odio', ''),
(110, 1, 'Amet ibendum', ''),
(110, 2, 'Amet ibendum', ''),
(110, 3, 'Amet ibendum', ''),
(110, 4, 'Amet ibendum', ''),
(110, 5, 'Amet ibendum', ''),
(110, 6, 'Amet ibendum', ''),
(110, 7, 'Amet ibendum', ''),
(110, 8, 'Amet ibendum', ''),
(110, 9, 'Amet ibendum', ''),
(111, 1, 'Laoreet sed', ''),
(111, 2, 'Laoreet sed', ''),
(111, 3, 'Laoreet sed', ''),
(111, 4, 'Laoreet sed', ''),
(111, 5, 'Laoreet sed', ''),
(111, 6, 'Laoreet sed', ''),
(111, 7, 'Laoreet sed', ''),
(111, 8, 'Laoreet sed', ''),
(111, 9, 'Laoreet sed', ''),
(115, 1, 'Phasellus purus', ''),
(115, 2, 'Phasellus purus', ''),
(115, 3, 'Phasellus purus', ''),
(115, 4, 'Phasellus purus', ''),
(115, 5, 'Phasellus purus', ''),
(115, 6, 'Phasellus purus', ''),
(115, 7, 'Phasellus purus', ''),
(115, 8, 'Phasellus purus', ''),
(115, 9, 'Phasellus purus', ''),
(116, 1, 'Elementum faucibus', ''),
(116, 2, 'Elementum faucibus', ''),
(116, 3, 'Elementum faucibus', ''),
(116, 5, 'Elementum faucibus', ''),
(116, 6, 'Elementum faucibus', ''),
(116, 7, 'Elementum faucibus', ''),
(116, 8, 'Elementum faucibus', ''),
(116, 9, 'Elementum faucibus', ''),
(117, 1, 'Nulla quam', ''),
(117, 2, 'Nulla quam', ''),
(117, 3, 'Nulla quam', ''),
(117, 5, 'Nulla quam', ''),
(117, 6, 'Nulla quam', ''),
(117, 7, 'Nulla quam', ''),
(117, 8, 'Nulla quam', ''),
(117, 9, 'Nulla quam', ''),
(118, 1, 'Amet ibendum', ''),
(118, 2, 'Amet ibendum', ''),
(118, 3, 'Amet ibendum', ''),
(118, 5, 'Amet ibendum', ''),
(118, 6, 'Amet ibendum', ''),
(118, 7, 'Amet ibendum', ''),
(118, 8, 'Amet ibendum', ''),
(118, 9, 'Amet ibendum', ''),
(133, 1, 'Amet ibendum', ''),
(133, 2, 'Amet ibendum', ''),
(133, 3, 'Amet ibendum', ''),
(133, 4, 'Amet ibendum', ''),
(133, 5, 'Amet ibendum', ''),
(133, 6, 'Amet ibendum', ''),
(133, 7, 'Amet ibendum', ''),
(133, 8, 'Amet ibendum', ''),
(133, 9, 'Amet ibendum', ''),
(144, 1, 'Sign up to newsletter', ''),
(144, 2, 'Sign up to newsletter', ''),
(144, 3, 'Sign up to newsletter', ''),
(145, 1, 'Follow us', '<div class=\"social_buttons\">\r\n<h2>Follow Us</h2>\r\n<ul>\r\n<li><a class=\"facebook\" title=\"Facebook\" href=\"#\">Facebook</a></li>\r\n<li><a class=\"twitter\" title=\"Twitter\" href=\"#\">Twitter</a></li>\r\n<li><a class=\"google\" title=\"Google+\" href=\"#\">Google</a></li>\r\n<li><a class=\"feed\" title=\"RSS Feed\" href=\"#\">RSS</a></li>\r\n<li><a class=\"youtube\" title=\"youtube\" href=\"#\">Youtube</a></li>\r\n</ul>\r\n</div>'),
(145, 2, 'Follow us', '<div class=\"social_buttons\">\r\n<h2>Follow Us</h2>\r\n<ul>\r\n<li><a class=\"facebook\" title=\"Facebook\" href=\"#\">Facebook</a></li>\r\n<li><a class=\"twitter\" title=\"Twitter\" href=\"#\">Twitter</a></li>\r\n<li><a class=\"google\" title=\"Google+\" href=\"#\">Google</a></li>\r\n<li><a class=\"feed\" title=\"RSS Feed\" href=\"#\">RSS</a></li>\r\n<li><a class=\"youtube\" title=\"youtube\" href=\"#\">Youtube</a></li>\r\n</ul>\r\n</div>'),
(145, 3, 'Follow us', '<div class=\"social_buttons\">\r\n<h2>Follow Us</h2>\r\n<ul>\r\n<li><a class=\"facebook\" title=\"Facebook\" href=\"#\">Facebook</a></li>\r\n<li><a class=\"twitter\" title=\"Twitter\" href=\"#\">Twitter</a></li>\r\n<li><a class=\"google\" title=\"Google+\" href=\"#\">Google</a></li>\r\n<li><a class=\"feed\" title=\"RSS Feed\" href=\"#\">RSS</a></li>\r\n<li><a class=\"youtube\" title=\"youtube\" href=\"#\">Youtube</a></li>\r\n</ul>\r\n</div>'),
(146, 1, 'Categories', ''),
(146, 2, 'Categories', ''),
(146, 3, 'Categories', ''),
(147, 1, 'Language', ''),
(147, 2, 'Language', ''),
(147, 3, 'Language', ''),
(148, 1, 'Current', ''),
(148, 2, 'Current', ''),
(148, 3, 'Current', ''),
(149, 1, 'logo', '<p><img src=\"modules/blockadvfooter/images/logo-footer.png\" alt=\"\" /></p>'),
(149, 2, 'logo', '<p><img src=\"modules/blockadvfooter/images/logo-footer.png\" alt=\"\" /></p>'),
(149, 3, 'logo', '<p><img src=\"modules/blockadvfooter/images/logo-footer.png\" alt=\"\" /></p>');


CREATE TABLE IF NOT EXISTS `_DB_PREFIX_loffc_block_lang` (
  `id_loffc_block` int(11) NOT NULL,
  `id_lang` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  PRIMARY KEY (`id_loffc_block`,`id_lang`)
) ENGINE=_MYSQL_ENGINE_ DEFAULT CHARSET=utf8;

INSERT INTO `_DB_PREFIX_loffc_block_lang` (`id_loffc_block`, `id_lang`, `title`) VALUES
(61, 1, 'Our offers'),
(61, 2, 'Our offers'),
(61, 3, 'Our offers'),
(61, 4, 'Our offers'),
(61, 5, 'Our offers'),
(61, 6, 'Our offers'),
(61, 7, 'Our offers'),
(61, 8, 'Our offers'),
(61, 9, 'Latest new'),
(62, 1, 'Information'),
(62, 2, 'Information'),
(62, 3, 'Information'),
(62, 4, 'Information'),
(62, 5, 'Information'),
(62, 6, 'Information'),
(62, 7, 'Information'),
(62, 8, 'Information'),
(62, 9, 'Information'),
(63, 1, 'New promotion'),
(63, 2, 'Information'),
(63, 3, 'Information'),
(63, 4, 'Information'),
(63, 5, 'Information'),
(63, 6, 'Information'),
(63, 7, 'Information'),
(63, 8, 'Information'),
(63, 9, 'New promotion'),
(64, 1, 'Sign up to newsletter'),
(64, 2, 'Sign up to newsletter'),
(64, 3, 'Sign up to newsletter'),
(65, 1, 'Follow us'),
(65, 2, 'Follow us'),
(65, 3, 'Follow us'),
(66, 1, 'Categories'),
(66, 2, 'Categories'),
(66, 3, 'Categories'),
(67, 1, 'Language'),
(67, 2, 'Language'),
(67, 3, 'Language');

";
?>